# Generated by Django 5.2.6 on 2025-10-23 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='imagen_url',
        ),
    ]
